{{- if or (not .Values.config.icinga_password_secret) (not .Values.config.alertmanager_bearer_token_secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signalilo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "signalilo.name" . }}
    helm.sh/chart: {{ include "signalilo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if not .Values.config.icinga_password_secret }}
  icinga_password: {{ required ".Values.config.icinga_password is required" .Values.config.icinga_password | b64enc | quote }}
{{- end }}
{{- if not .Values.config.alertmanager_bearer_token_secret }}
  alertmanager_bearer_token: {{ required ".Values.config.alertmanager_bearer_token is required" .Values.config.alertmanager_bearer_token | b64enc | quote }}
{{- end }}
{{- end -}}
