kind: Secret
apiVersion: v1
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  alertmanager.yaml: |-
    {{ .Files.Get "alertmanager.yaml" | b64enc }}