apiVersion: v1
kind: Secret
metadata:
  namespace: dynatrace
  name: oneagent
data:
  apiToken: {{ required ".Values.config.apiToken is required" .Values.config.apiToken | b64enc | quote }}
  paasToken: {{ required ".Values.config.paasToken is required" .Values.config.paasToken | b64enc | quote }}

